version: '3.9'

services:

  db:
    image: postgres:15-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


#version: '3.9'
#
#services:
#
#  db:
#    image: postgres:15-alpine
#    restart: always
#    # set shared memory limit when using docker-compose
#    shm_size: 128mb
#    ports:
#      - 5432:5432
#
#      # or set shared memory limit when deploy via swarm stack
#    #volumes:
#    #  - type: tmpfs
#    #    target: /dev/shm
#    #    tmpfs:
#    #      size: 134217728 # 128*2^20 bytes = 128Mb
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#        - POSTGRES_USER=${POSTGRES_USER}
#        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:
##  adminer:
##    image: adminer
##    restart: always
##    ports:
##      - 8080:8080