INSERT INTO users(default_address_id, is_block)
VALUES
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false),
    (1, false),
    ( 2, false),
    (3, false),
    (4, false);